### ISSUE TITLE
Update bower because is now not supported

### ISSUE THREAD

**Issue by gustawdaniel** [gustawdaniel/geo_local#2]
> https://bower.io/

**Comment by gustawdaniel** [comment]
Migration to npm not works 

```
npm i ---verbose
npm info it worked if it ends with ok
npm verb cli [ '/home/daniel/.nvm/versions/node/v10.7.0/bin/node',
npm verb cli   '/home/daniel/.nvm/versions/node/v10.7.0/bin/npm',
npm verb cli   'i',
npm verb cli   '---verbose' ]
npm info using npm@6.1.0
npm info using node@v10.7.0
npm verb npm-session f8c622ae34bab5c4
npm info lifecycle @~preinstall: @
npm timing stage:loadCurrentTree Completed in 41ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 181425ms
npm verb stack Error: Command failed: /usr/bin/git checkout ^1.0.2
npm verb stack error: pathspec '^1.0.2' did not match any file(s) known to git.
npm verb stack 
npm verb stack     at ChildProcess.exithandler (child_process.js:291:12)
npm verb stack     at ChildProcess.emit (events.js:182:13)
npm verb stack     at maybeClose (internal/child_process.js:961:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
npm verb cwd /home/daniel/exp/geo_local
npm verb Linux 4.15.0-43-generic
npm verb argv "/home/daniel/.nvm/versions/node/v10.7.0/bin/node" "/home/daniel/.nvm/versions/node/v10.7.0/bin/npm" "i" "---verbose"
npm verb node v10.7.0
npm verb npm  v6.1.0
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout ^1.0.2
npm ERR! error: pathspec '^1.0.2' did not match any file(s) known to git.
npm ERR! 
npm verb exit [ 1, true ]
npm timing npm Completed in 181899ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2019-01-16T17_20_01_779Z-debug.log
```

![screenshot from 2019-01-16 18-20-55](https://user-images.githubusercontent.com/16663028/51266405-7be9a800-19bb-11e9-8dd2-90a09e6cf6f5.png)
